<?php

/**
 * Overview Page assets from Figma → Latest Designs → Overview Page
 * (WF-2026 - Tau Mafia Hubsite, node 3566:19444)
 * Prefer local files under /assets/overview; fall back to Figma MCP URLs.
 */
return [
    'wf_logo' => 'wf-logo-horizontal.png',
    'arrow_drop_down' => 'arrow-drop-down.svg',
    'login' => 'login.svg',
    'js2_logo' => 'js2-logo.png',
    'masthead_char' => 'masthead-char.png',
    'masthead_overlay' => 'masthead-overlay.png',
    'line' => 'line.svg',
    'platform_pc' => 'platform-pc.svg',
    'platform_steam' => 'platform-steam.svg',
    'platform_epic' => 'platform-epic.svg',
    'platform_switch' => 'platform-switch.svg',
    'platform_switch2' => 'platform-switch2.svg',
    'platform_ps' => 'platform-ps.svg',
    'platform_xbox' => 'platform-xbox.svg',
    'platform_apple' => 'platform-apple.svg',
    'platform_google' => 'platform-google.svg',
    'hub_union' => 'hub-union.png',
    'hub_edge_bottom' => 'hub-edge-bottom.png',
    'hub_border_trim' => 'hub-border-trim.png',
    'hub_pattern' => 'hub-pattern.png',
    'hub_tile_1' => 'hub-tile-1.png',
    'hub_tile_2' => 'hub-tile-2.png',
    'hub_tile_3' => 'hub-tile-3.png',
    'arrow_1' => 'arrow-1.svg',
    'arrow_2' => 'arrow-2.svg',
    'subnav_texture' => 'subnav-texture.png',
    'noise' => 'noise-texture.png',
    'update_summary_bg' => 'update-summary-bg.png',
    'divider' => 'divider-warframe0058.png',
    'divider_bone' => 'divider-warframe0058.png',
    'check_thumb' => 'check-thumb.png',
    'tau_thumb' => 'tau-thumb.png',
    'section_bg' => 'section-bg.png',
    'smoke' => 'smoke.png',
    'black_rain' => 'black-rain.png',
    'rings' => 'rings.png',
    'starchart_map' => 'starchart-map.png',
    'planet_fornax' => 'planet-fornax.png',
    'planet_perita' => 'planet-perita.png',
    'rocks_dust' => 'rocks-dust.png',
    'sentient_structure' => 'sentient-structure.png',
    'sentient_structure_b' => 'sentient-structure-b.png',
    'brysko_bg' => 'brysko-bg.png',
    'ability_card' => 'ability-card.png',
    'ability_1' => 'ability-1.svg',
    'ability_2' => 'ability-2.svg',
    'ability_3' => 'ability-3.svg',
    'ability_4' => 'ability-4.svg',
    'passive' => 'passive.svg',
    'ability_frame' => 'ability-frame.svg',
    'divider_jagged' => 'divider-jagged.png',
    'tenno_mechanic' => 'tenno-mechanic.png',
    'tenno_card_1' => 'tenno-card-1.png',
    'tenno_card_2' => 'tenno-card-2.png',
    'tenno_card_3' => 'tenno-card-3.png',
    'qol_texture' => 'qol-texture.png',
    'divider_1' => 'divider-1.png',
    'divider_2' => 'divider-2.png',
    'divider3_top' => 'divider3-top.png',
    'divider3_bottom' => 'divider3-bottom.png',
    'divider3' => 'divider3-top.png',
    'qol_fence' => 'qol-fence.png',
    'qol_back' => 'qol-back.png',
    'qol_1a' => 'qol-1a.png',
    'qol_1b' => 'qol-card-nidus.png',
    'qol_2a' => 'qol-2a.png',
    'qol_2b' => 'qol-card-focus.png',
    'qol_3a' => 'qol-3a.png',
    'qol_3_mid' => 'qol-3b-mid.png',
    'qol_3b' => 'qol-card-appearance.png',
    'qol_4' => 'qol-card-riven.png',
    'soundtrack_bg' => 'soundtrack-bg.png',
    'soundtrack_cover' => 'soundtrack-cover.png',
    'soundtrack_cover_alt' => 'soundtrack-cover-alt.png',
    'soundtrack_vinyl' => 'soundtrack-vinyl.png',
    'spotify' => 'spotify-icon.png',
    'apple_music' => 'apple-music-icon.png',
    'bandcamp' => 'bandcamp-icon.png',
    'youtube' => 'youtube-icon.svg',
];
